// See https://aka.ms/new-console-template for more information
using AlxCourseHomework.MailingService;
using AlxCourseHomework.MaterialAssignments;
using AlxCourseHomework.MaterialAssignments.Project1;

Console.WriteLine("Email Service");
Console.WriteLine("_____________");
Homework1Test.Run();
Console.WriteLine("\nExercise 1.1");
Console.WriteLine("____________\n");
ExercisesPage12.Run11();
Console.WriteLine("\nExercise 1.2");
Console.WriteLine("____________\n");
ExercisesPage12.Run12();
Console.WriteLine("\nExercise 1.3");
Console.WriteLine("____________\n");
ExercisesPage12.Run13(); 
Console.WriteLine("\nExercise 2.1");
Console.WriteLine("____________\n");
ExercisesPage17.Run21();
Console.WriteLine("\nExercise 2.2");
Console.WriteLine("____________\n");
ExercisesPage17.Run22();
Console.WriteLine("\nExercise 3.1");
Console.WriteLine("____________\n");
ExercisesPage19.Run31();
Console.WriteLine("\nExercise 3.2");
Console.WriteLine("____________\n");
ExercisesPage19.Run32();
Console.WriteLine("\nExercise 4.1");
Console.WriteLine("____________\n");
ExercisesPage21.Run41();
Console.WriteLine("\nExercise 4.2");
Console.WriteLine("____________\n");
ExercisesPage21.Run42();
Console.WriteLine("\nExercise 5.1");
Console.WriteLine("____________\n");
ExercisesPage23.Run51();
Console.WriteLine("\nExercise 5.2");
Console.WriteLine("____________\n");
ExercisesPage23.Run52();
Console.WriteLine("\nExercise 5.3");
Console.WriteLine("____________\n");
ExercisesPage23.Run53();
Console.WriteLine("\nExercise 6.1");
Console.WriteLine("____________\n");
ExercisesPage25.Run61();
Console.WriteLine("\nExercise 6.2");
Console.WriteLine("____________\n");
ExercisesPage25.Run62();
Console.WriteLine("\nExercise 7.1");
Console.WriteLine("____________\n");
ExercisesPage45.Run71();
Console.WriteLine("\nExercise 7.2");
Console.WriteLine("____________\n");
ExercisesPage45.Run72();