using alxkurs.Lessons;
using alxkurs.Assigments;
using alxkurs.Lessons.M1.L2;
using alxkurs.Assigments.M2;
using alxkurs.Lessons.M2.L1;
using alxkurs.Lessons.M2.L2;
using alxkurs.Assigments.M2.L2;

Console.Write("Mateusz");
Console.WriteLine("\nALX Kurs\n--------------");
// L1ObjectWariables.Run2();

// L1SimpleVariables.Run(); 
//L1Strings.Run();
//L1Spiders.Run();
//AssigmentsDemo.Run();
//L2Conditionals.Run();
//L2EnumsSwitch.Run();
//SeniorityServiceTest.Run(); 
//L1Arrays.Run();
//L1Lists.Run(); 
//L1Arrays.Run1();
//L1Loops.RunForeach();
//L1Loops.RunFor();
//L1Loops.RunDoWhile();
//L1Dictionaries.Run1(); 
//L2GettersAndSetters.Run();
//BookStorageApp.Run();
//L2Encapsulation.Run();
//L2Interfaces.Run();
L2Inharitance.Run();